version: '3.5'

services: 
    influxdb:
      image: influxdb
      container_name: influxdb
      ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
      env_file:
        - 'env.influxdb'
      volumes:
        # Data persistency
        # sudo mkdir -p /influxdb
        - ./volumes/influxdb:/var/lib/influxdb

    telegraf:
      image: telegraf
      container_name: telegraf
      links:
        - influxdb
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

#If you want to run Telegraf, edit the telegraf.conf to yours needs and:
# $ docker exec telegraf telegraf

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3001:3000"
      env_file:
        - 'env.grafana'
      user: "0"
      links:
        - influxdb
      volumes:
        # Data persistency
        # sudo mkdir -p /grafana; chown 472:472 /grafana
        - ./volumes/grafana:/var/lib/grafana
        
    seq:
      image: datalust/seq
      container_name: seq
      ports: 
        - "8084:80"
        - "5341:5341"
      volumes: 
        - ./volumes/seq:/data
      environment: 
        - ACCEPT_EULA=Y
    consul:
      container_name: consul
      image: consul
      ports:
        - "8500:8500"
        - "8600:8600"  

    sqlserver:
      image: mcr.microsoft.com/mssql/server
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password

    redis:
      image: redis:alpine
      ports:
        - 6379:6379
